students=["Athira","Anvika","Vimal","Rohith","Anu","Anil"]
print("Before Append")
print(students)
students.append("Akhil")
print("After append")
print(students)
students.insert(1,"Rahul")
print(students)
students.remove("Vimal")
print(students)
students.pop()
print(students)
students.pop(1)
print(students)
print(len(students))
students.sort()
print(students)
students.reverse()
print(students)